language: python
python:
  - '2.7'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install firefox
  - cp mysite/mysite/settings/local_conf_example.py mysite/mysite/settings/local_conf.py
  - cp fab_settings.py.example fab_settings.py
install:
  - pip install -r requirements.txt
script:
  - cd mysite/
  - python manage.py test
deploy:
  provider: opsworks
  access_key_id: AKIAJOC53YQJD734SJEA
  secret_access_key: 
    secure: qCcOnqQV48Xe2YltK17Gyp18zbk2IkiVXyrRFig16ntVQ18+gTIEOOoQbAtkgdiIiZ6p4/kCZcXx8TMPbllt/rdR2GLC5AP/3p5T1l5i2pj+UIIiupY2I1hkhH68tubmhvpll7zwsQT1PE/PsduPnFpJuV1nMxN0yLRWcKFwM77mniyuJZ2bzW/2lhwcWkJn0E5MLIe7RWXw0+K5sWl59V4TKNS3aQuyMhcE6bdgYJq5tk0nXiKFwER+wt4U/Om1yzoVnCJRxurJFOk19Lc0reEhUgkG3kBcg98BYB4+RtvAhbyouLnVx48Q8AQGj6O4avNLwqqt5/HxV11Iv5EJSraEm3Rlu5czZr+baqyMBJnL9akZcUByZvQEnloxuPMpJUQqSJTErbImJnB4wOgt2moQE+5Xw2/ZVbu2AGR16ovRu+2zTUm/hVfkweNKhDrGkTMOLs+/tCc0zuKudQmKpyo4JyL0R3y/zF9KEdyEJIzRqbk83bNDkciph0YnCf608FuhuC+p2/1JBV2Bs6xTzJQHZfAyo1NyEUWa38x/eoq2WMts3eGJoOwXpR4JNn6Eztj5IILnvz9DvK6z8+LbsTz6E7x0pnA8uj5oKFOCPhJRpZo71y+X0lPiNB7g7gsFrb5evB12zirLk+msWFbM2FBf1KkY2z5jw3s0tWdPfG4=
  app-id: 010c3e30-5ac2-4525-ad65-dd44ab417932
  on:
    repo: derdmitry/socraticqs2
AKIAJCNGFZD565BNSNHA:
  secure: aJHDtqUHR0nf+Se4ITbZF/qexNmN6+LjribPHvhFU5qM9BN5jDhUFvpCMyIc0eIPkPna7rwVQft+n8WEas6npaGIsZ2K9q4QB2LhYolxF79HdhoQPy5xuSlIBvWQyGqGRu090qD+DTqisNX7ztH0zL6mv+Pw2Q6Xh2EiHlLVcP00l4FzduA9nqELx+KvKoZvfMRq3qzfaTqHQJcW/4E2+wU11uGvyPjhxLsoGCAQhgolBM3Ida6JCAjkc+UaNcTfPwHeV78JFpDHsm/E3WmRDFDIbVIe11TDziCMZv/iUp0Pu225rI9nf4+1oSyuQ90hNTP2nai8d4pEyZc/GZYc22NFegKqDhjSNKNZXYiqXg5a0blLOQRSQyeNwG+sLJ/ilxDHOKfWzy4uX+inSNT6BJxWKKKuz6vVxbdsBJKn20MewL2eucpkO5dBLWAx38kX7hKGxQGY/dOzCmrYkn4gr7tX4bH1d84pDt59bonXT3GLrtQzPJBHM5yv0qYhs4++X30jmEGJT2hvBdxZe4XLbaeCItBkmyK2DTjUcjYk0ZyoQSjSeHc85T7r5sY8Ou8HIW3Witx41r9SZoAFXW3dEnWJiHWRyBpu3LirqCm2kVV7KuEJ+J+C4+oVBSX7D0WB7j3tn5ZxMi4GYKZdWHVxSxKCDR8czqqrcRwDMknUZoE=
