language: python
python:
  - "2.7"
# preinstall packages
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
