language: python
python:
  - "2.7"
# preinstall packages
before_install:
#- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install firefox
  - cp mysite/mysite/settings/local_conf_example.py mysite/mysite/settings/local_conf.py
  - cp fab_settings.py.example fab_settings.py
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  - cd mysite/
  - Xvfb :99 & export DISPLAY=:99 python manage.py test
